### ISSUE TITLE
Improvement => placeholder

### ISSUE THREAD

**Issue by alicerocheman** [halt-hammerzeit/react-phone-number-input#45]
Hi there,

Thank you so much for your reactivity on my previous issue! 

I created this issue for an improvement idea regarding placeholders. This came up because my coworker added a placeholder for french numbers to your component on our project. As the whole point of using your component is that the users will be able to register a phone from any country, this is far from ideal.

Would you consider adding a dynamic placeholder, since you already know the format of the number needed in all countries? It could dynamically change according to the selected country & international/local version of the number.

I believe it would be an incredible improvement on your component. :)

**Comment by halt-hammerzeit** [comment]
Describe in more detail how this placeholder would behave.
Do you mean the usual HTML5 `placeholder` attribute?

**Comment by halt-hammerzeit** [comment]
Or maybe you were talking about something like `maskChar` property from `react-input-mask`
http://sanniassin.github.io/react-input-mask/demo.html
Since phone numbers aren't deterministic there are many countries for which phone number can be of variable length and several formats therefore I think such feature wouldn't make much sense. And also I don't like masked inputs personally so I won't be implementing them.
If anyone decides to implement such a feature they would start with `maskChar` property in `input-format` library and then add a `maskChar` property in this library.
Alternatively one could supply an HTML5 `placeholder={this.generatePlaceholder()}` using the already existing `country` and `onCountryChange` properties.
