### ISSUE TITLE
onBlur triggers a 'ReferenceError: parse is not defined'

### ISSUE THREAD

**Issue by alicerocheman** [halt-hammerzeit/react-phone-number-input#6]
Hi,

I'm using your awesome library, so first of all thank you :)

I'm encountering a bit of a problem, trying to use onBlur. onFocus works fine, but onBlur triggers an error, even when calling an empty function...

Any way you could help with this? Have you seen this problem yourself?

Thanks

**Comment by halt-hammerzeit** [comment]
Hello.
I can fix it if you give me the details.
Like what exactly are you doing in your code and how exactly are you trying to do that.
And what is the exact error.

**Comment by alicerocheman** [comment]
Hi, thank you for answering so quickly!

I use a Material ui interface on React.
I wasn't willing to "reprogram" all the Material TextField behavior, so I put a Material Textfield underneath your Phone component, and I force the focused and unfocused style of the Material Textfield when the Phone gets focused and unfocused. It works fine with the onFocused but the onBlur triggers an error (no matter what I do in the called function, even if I do nothing)
If I remove the onBlur, everything works fine.
```
<Phone 
	id="phoneNumber"
	name="phoneNumber"
	country={regionCode}
	value={this.state.phoneValue}
	onFocus={this.handlePhoneFocus}
	onBlur={this.handlePhoneBlur}
	onChange={value => {this.handlePhoneValueChange(value);}}
	style={styles.phoneIntl}
/>


handlePhoneBlur(){
	let newState = {
		...this.state,
		phoneFocused:false
	};
	this.setState(newState);
}
```

**Comment by halt-hammerzeit** [comment]
Post me the full text of the error

**Comment by halt-hammerzeit** [comment]
Ok, I see the error now

**Comment by halt-hammerzeit** [comment]
Ok, try to `npm install input-format@latest` and the error should be absent now.

**Comment by alicerocheman** [comment]
wow, yeah it worked, thank you so much!

**Comment by sompylasar** [comment]
Fixed in `react-phone-number-input@0.6.10` by updating `input-format` to `0.1.3`
* https://github.com/halt-hammerzeit/react-phone-number-input/commit/8a2b8c5e3920112bef7e8552362908e025073ab5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L14
 * https://github.com/halt-hammerzeit/input-format/commit/8bb23bc1d5ea7fea8005961b15ac7ed60e3d0558

@alicerocheman Just installing the latest version of a package that is a dependency of a package you're actually using only fixes the error on your machine. To really fix that you need to update react-phone-number-input after it has updated the dependency which was the source of the error.

**Comment by halt-hammerzeit** [comment]
@sompylasar True.
But at the same time if it was `^react-phone-number-input@0.6.0` then it will always update to the latest one during `npm install`.
Unless Yarn is used of course which always locks exact version numbers.

**Comment by sompylasar** [comment]
> Unless Yarn is used of course which always locks exact version numbers.

1) If the version in `package.json` is not specific, 2) unless `yarn`, 3) unless `npm shrinkwrap` – too many assumptions, especially when recommending to a newbie who could even not know all that.

**Comment by halt-hammerzeit** [comment]
Yes, updating to the latest version is the best way to go, speaking of which why aren't you updated to the latest `0.8.0`

**Comment by sompylasar** [comment]
I don't use this component. I just stumbled upon an issue with a confusing suggestion which "helped" only at the first sight, and no reference to the commit and version which have the issue fixed.

**Comment by halt-hammerzeit** [comment]
Oh, I see

**Comment by alicerocheman** [comment]
@sompylasar thanks! are you actually stalking me to help everywhere I get stuck? ;) Impressively helpful, it's much appreciated ^^

**Comment by halt-hammerzeit** [comment]
Wow, we have a knight here, I see.
Kinda cute.

**Comment by sompylasar** [comment]
:facepalm: Nope, I'm stalking good projects such as `react-phone-number-input` because I know I may need them later, and improving their quality. Kinda investment into my own future. To find good projects I look around, this includes looking into other people's GitHub activity stream. I watch all comments from `eslint-plugin-import` as I use it in production, that's how via @alicerocheman's issue I stumbled upon `react-phone-number-input` and `input-format`. I wouldn't be able to find them unless I specifically search and research, which at the time I'll need them I won't be able to afford.

**Comment by halt-hammerzeit** [comment]
Just found a bug when using with `redux-form` caused by `onBlur(event)`.
Fixed: https://github.com/halt-hammerzeit/input-format/commit/02fe2b4a525bb74d5f9b5bc56ef5f44117461b6c
(completely reinstall `node_modules` for the new `input-format` module install)
